@startuml
class server.BoardMgr {
- ClientMgr manager
- IClient clientManager
+ void login(IClient)
+ boolean validUsername(String)
+ Set<IClient> getClients()
+ void syncClientList()
+ void quitClient(String)
+ void kickClient(String)
+ void removeAllClients()
+ void broadcastMsg(ICanvasMsg)
+ byte[] sendCurrentCanvas()
+ void sendExistCanvas(byte[])
+ void cleanCanvas()
+ void broadcastChat(String)
+ void syncChatHistory(IClient)
}
interface canvas.ICanvasMsg {
~ String getDrawState()
~ String getDrawType()
~ Color getColor()
~ Point getPoint()
~ String getText()
~ String getUsername()
}
class canvas.CanvasMsg {
- {static} long serialVersionUID
- String drawState
- String drawType
- Color color
- Point point
- String text
- String username
+ String getDrawState()
+ String getDrawType()
+ Color getColor()
+ Point getPoint()
+ String getText()
+ String getUsername()
}
class client.User {
+ {static} void main(String[])
}
class client.Client {
- {static} long serialVersionUID
- String username
- boolean isManager
- boolean hasAccess
- Canvas canvas
- IBoardMgr server
- ConcurrentHashMap<String,Point> points
- String canvasName
- String canvasPath
- JFrame window
- {static} int windowWidth
- {static} int windowHeight
- {static} String iconDirPath
- Color bgColor
- LineBorder border
- LineBorder antiBorder
- JButton blackBt
- JButton greenBt
- ArrayList<JButton> colorBts
- JButton colorUse
- JButton freeBt
- ArrayList<JButton> drawBts
- {static} int drawBtWidth
- {static} int drawBtHeight
- JButton newBt
- ArrayList<JButton> funcBts
- {static} int funcBtWidth
- {static} int funcBtHeight
- DefaultListModel<String> clientList
- DefaultListModel<String> chatHistory
- JTextField chatMsg
- JScrollPane chatWindow
~ ActionListener actionListener
+ String getName()
+ void setName(String)
+ void setAsManager()
+ boolean needAccess(String)
+ boolean getAccess()
+ void setAccess(boolean)
+ void syncClientList(Set<IClient>)
+ void syncCanvas(ICanvasMsg)
+ void cleanCanvas()
+ byte[] getCurrentCanvas()
+ void overrideCanvas(byte[])
+ void forceQuit()
+ void syncChat(String)
+ DefaultListModel<String> getChatHistory()
+ void syncChatHistory(DefaultListModel<String>)
+ void mgrOpen()
- void mgrSave()
- void mgrSaveAs()
+ void selectButton(JButton,ArrayList<JButton>)
+ ImageIcon resizeIcon(String,int,int)
+ void renderUI(IBoardMgr)
}
interface client.IClient {
~ String getName()
~ void setName(String)
~ void setAsManager()
~ boolean needAccess(String)
~ boolean getAccess()
~ void setAccess(boolean)
~ void syncClientList(Set<IClient>)
~ void syncCanvas(ICanvasMsg)
~ void cleanCanvas()
~ byte[] getCurrentCanvas()
~ void overrideCanvas(byte[])
~ void forceQuit()
~ void syncChat(String)
~ DefaultListModel<String> getChatHistory()
~ void syncChatHistory(DefaultListModel<String>)
~ void renderUI(IBoardMgr)
}
class server.Server {
+ {static} void main(String[])
}
interface server.IBoardMgr {
~ void login(IClient)
~ boolean validUsername(String)
~ Set<IClient> getClients()
~ void syncClientList()
~ void quitClient(String)
~ void kickClient(String)
~ void removeAllClients()
~ void broadcastMsg(ICanvasMsg)
~ byte[] sendCurrentCanvas()
~ void sendExistCanvas(byte[])
~ void cleanCanvas()
~ void broadcastChat(String)
~ void syncChatHistory(IClient)
}
class client.ClientMgr {
- Set<IClient> clientList
+ Set<IClient> getClientList()
+ void addClient(IClient)
+ void delClient(IClient)
+ boolean hasNoClient()
}
class canvas.Canvas {
- {static} long serialVersionUID
- boolean isManager
- String drawType
- Color color
- Point start
- String text
- IBoardMgr boardMgr
- Graphics2D g2
- BufferedImage frame
- BufferedImage prevFrame
+ {static} int canvasWidth
+ {static} int canvasHeight
+ {static} BasicStroke defaultStroke
+ {static} BasicStroke thickStroke
+ {static} Font defaultFont
+ {static} String paintStart
+ {static} String painting
+ {static} String paintEnd
+ void paintComponent(Graphics)
+ Color getColor()
+ Graphics2D getG2()
+ BufferedImage getFrame()
+ void renderFrame(BufferedImage)
+ void cleanCanvas()
+ void saveCanvas()
+ BufferedImage getCanvasImage()
+ void free()
+ void line()
+ void circle()
+ void triangle()
+ void rectangle()
+ void text()
+ void eraser()
+ Shape drawLine(Point,Point)
+ Shape drawCircle(Point,Point)
+ Shape drawTriangle(Point,Point)
+ Shape drawRectangle(Point,Point)
+ void black()
+ void white()
+ void gray()
+ void silver()
+ void maroon()
+ void red()
+ void purple()
+ void fuchsia()
+ void green()
+ void lime()
+ void olive()
+ void yellow()
+ void navy()
+ void blue()
+ void teal()
+ void aqua()
}
class client.Creator {
+ {static} void main(String[])
}


server.IBoardMgr <|.. server.BoardMgr
java.io.Serializable <|.. server.BoardMgr
java.rmi.server.UnicastRemoteObject <|-- server.BoardMgr
java.rmi.Remote <|-- canvas.ICanvasMsg
canvas.ICanvasMsg <|.. canvas.CanvasMsg
java.rmi.server.UnicastRemoteObject <|-- canvas.CanvasMsg
client.IClient <|.. client.Client
java.rmi.server.UnicastRemoteObject <|-- client.Client
java.rmi.Remote <|-- client.IClient
java.rmi.Remote <|-- server.IBoardMgr
canvas.JComponent <|-- canvas.Canvas
@enduml